---
name: eliud_core_main
description: Eliud core main is the main core eliud package. It's a required package
  for all eliud apps. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_core_main
version: 1.3.0
environment:
  sdk: '>=3.1.0 <4.0.0'
#  sdk: '>=3.2.0 <4.0.0'
#  flutter: '>=3.0.0'
dependencies:
  bloc: ^8.1.4
  datetime_picker_formfield_new: ^2.1.0
  cloud_functions: ^5.1.3
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2 
  flutter_bloc: ^8.1.6
  flutter_colorful_tab: ^0.1.1
  flutter_colorpicker: ^1.1.0
  get_thumbnail_video:
    path: ../../external-libs/video_thumbnail
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image: ^4.2.0
  pdfx_plugin: ^1.1.0
  pointer_interceptor: ^0.10.1+2
  sign_in_with_apple: ^6.1.2
  transparent_image: ^2.0.1
  tuple: ^2.0.2
  universal_html: ^2.2.4
  eliud_core_helpers: ^1.3.0
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.3
  equatable: ^2.0.5
  collection: ^1.18.0
  meta: ^1.15.0
  crypto: ^3.0.5
  path: ^1.9.0
dev_dependencies:
  build_runner: ^2.4.12
  eliud_generator: ^1.1.7
#  lints: ^5.0.0
flutter:
  uses-material-design: true


dependency_overrides:
  eliud_core:
    path: ../../eliud/eliud_core
  eliud_core_helpers:
    path: ../../eliud/eliud_core_helpers
  eliud_core_model:
    path: ../../eliud/eliud_core_model
  eliud_generator:
    path: ../../eliud/eliud_generator
  eliud_pkg_apps:
    path: ../../eliud/eliud_pkg_apps
  eliud_pkg_chat:
    path: ../../eliud/eliud_pkg_chat
  eliud_pkg_chat_model:
    path: ../../eliud/eliud_pkg_chat_model
  eliud_pkg_create:
    path: ../../eliud/eliud_pkg_create
  eliud_pkg_create_model:
    path: ../../eliud/eliud_pkg_create_model
  eliud_pkg_etc:
    path: ../../eliud/eliud_pkg_etc
  eliud_pkg_etc_model:
    path: ../../eliud/eliud_pkg_etc_model
  eliud_pkg_feed:
    path: ../../eliud/eliud_pkg_feed
  eliud_pkg_feed_model:
    path: ../../eliud/eliud_pkg_feed_model
  eliud_pkg_follow:
    path: ../../eliud/eliud_pkg_follow
  eliud_pkg_follow_model:
    path: ../../eliud/eliud_pkg_follow_model
  eliud_pkg_fundamentals:
    path: ../../eliud/eliud_pkg_fundamentals
  eliud_pkg_fundamentals_model:
    path: ../../eliud/eliud_pkg_fundamentals_model
  eliud_pkg_medium:
    path: ../../eliud/eliud_pkg_medium
  eliud_pkg_medium_model:
    path: ../../eliud/eliud_pkg_medium_model
  eliud_pkg_membership:
    path: ../../eliud/eliud_pkg_membership
  eliud_pkg_membership_model:
    path: ../../eliud/eliud_pkg_membership_model
  eliud_pkg_notifications:
    path: ../../eliud/eliud_pkg_notifications
  eliud_pkg_notifications_model:
    path: ../../eliud/eliud_pkg_notifications_model
  eliud_pkg_pay:
    path: ../../eliud/eliud_pkg_pay
  eliud_pkg_shop:
    path: ../../eliud/eliud_pkg_shop
  eliud_pkg_shop_model:
    path: ../../eliud/eliud_pkg_shop_model
  eliud_pkg_text:
    path: ../../eliud/eliud_pkg_text
  eliud_pkg_text_model:
    path: ../../eliud/eliud_pkg_text_model
  eliud_pkg_wizards:
    path: ../../eliud/eliud_pkg_wizards
  eliud_pkg_workflow:
    path: ../../eliud/eliud_pkg_workflow
  eliud_pkg_workflow_model:
    path: ../../eliud/eliud_pkg_workflow_model
  eliud_stl_mona:
    path: ../../eliud/eliud_stl_mona
  eliud_stl_mona_model:
    path: ../../eliud/eliud_stl_mona_model
