---
name: eliud_core_main
description: Eliud core main is the main core eliud package. It's a required package
  for all eliud apps. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_core_main
version: 1.0.2
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  bloc: ^8.1.2
  datetime_picker_formfield_new: ^2.1.0
  firebase_auth: ^4.15.2
  firebase_storage: ^11.5.5
  flutter_bloc: ^8.1.3
  flutter_colorful_tab: ^0.1.0
  flutter_colorpicker: ^1.0.3
  get_thumbnail_video: ^0.6.1
  google_sign_in: ^6.2.0
  http: ^1.1.2
  image: ^4.1.3
  pdfx_plugin: ^1.1.0
  pointer_interceptor: ^0.9.3+7
  sign_in_with_apple: ^5.0.0
  transparent_image: ^2.0.1
  tuple: ^2.0.2
  universal_html: ^2.2.4
  eliud_core_helpers: ^1.0.0
  flutter:
    sdk: flutter

  cloud_firestore: ^4.13.5
  equatable: ^2.0.5
  collection: ^ 1.18.0
  meta: ^1.10.0
  crypto: ^3.0.3
  path: ^1.8.3                                                                                       # ANDROID IOS LINUX MACOS WEB WINDOWS

dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator: ^1.1.7
  lints: ^3.0.0
flutter:
  uses-material-design: true
