---
name: eliud_core_main
description: Eliud core main is the main core eliud package. It's a required package for all eliud apps. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_core_main
version: 1.0.0
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  bloc: ^8.1.2                                                                                      # ANDROID IOS LINUX MACOS WEB WINDOWS
  firebase_auth: ^4.15.0                                                                            # ANDROID IOS LINUX MACOS WEB WINDOWS
  firebase_storage: ^11.5.3                                                                         # ANDROID IOS LINUX MACOS WEB WINDOWS
  flutter_bloc: ^8.1.3                                                                              # ANDROID IOS LINUX MACOS WEB WINDOWS
  flutter_colorful_tab: ^0.1.0                                                                      # ANDROID IOS LINUX MACOS WEB WINDOWS
  flutter_colorpicker: ^1.0.3                                                                       # ANDROID IOS LINUX MACOS WEB WINDOWS
  get_thumbnail_video: ^0.6.1                                                                       # ANDROID IOS             WEB
  google_sign_in: ^6.1.6                                                                            # ANDROID IOS LINUX MACOS WEB WINDOWS
  http: ^1.1.0                                                                                      # ANDROID IOS LINUX MACOS WEB WINDOWS
  image: ^4.1.3                                                                                     # ANDROID IOS LINUX MACOS WEB WINDOWS
  pdfx: ^2.5.0                                                                                      # ANDROID IOS       MACOS WEB WINDOWS
  pointer_interceptor: ^0.9.3+7                                                                     # ANDROID IOS LINUX MACOS WEB WINDOWS
  sign_in_with_apple: ^5.0.0                                                                        # ANDROID IOS LINUX MACOS WEB WINDOWS
  transparent_image: ^2.0.1                                                                         # ANDROID IOS LINUX MACOS WEB WINDOWS
  tuple: ^2.0.2                                                                                     # ANDROID IOS LINUX MACOS WEB WINDOWS
  universal_html: ^2.2.4                                                                            # ANDROID IOS LINUX MACOS WEB WINDOWS

  eliud_core_helpers:
    path: ../eliud_core_helpers

  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
